name: Release Package

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          current_version=$(grep -oP 'version = "\K[^"]+' Cargo.toml) # Extract current version from Cargo.toml
          echo "::set-output name=current_version::$current_version"

      - name: Bump version
        id: bump_version
        run: |
          current_version=${{ steps.get_version.outputs.current_version }}
          # Your versioning logic here, for example:
          # Increment patch version
          new_version=$(echo $current_version | awk -F. '{$NF++;print}' OFS=.)
          echo "New version: $new_version"
          # Update Cargo.toml with the new version
          sed -i "s/version = \"$current_version\"/version = \"$new_version\"/" Cargo.toml


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.bump_version.outputs.new_version }}
          release_name: Release v${{ steps.bump_version.outputs.new_version }}
          draft: false
          prerelease: false
