name: Release Package

on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          current_version=$(grep -oP 'version = "\K[^"]+' Cargo.toml) # Extract current version from Cargo.toml
          echo "::set-output name=current_version::$current_version"

      - name: Bump version
        id: bump_version
        run: |
          current_version=${{ steps.get_version.outputs.current_version }}
          # Your versioning logic here, for example:
          # Increment patch version
          new_version=$(echo $current_version | awk -F. '{$NF++;print}' OFS=.)
          echo "New version: $new_version"
          # Update Cargo.toml with the new version
          sed -i "s/version = \"$current_version\"/version = \"$new_version\"/" Cargo.toml
      - name: install git
        run: sudo apt-get install git
      - name: Git force push
        run: Git push --force

      - name: cargo publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
