name: Release Package
permissions:
  contents: read
  pages: write 
on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: publish
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v2
      with:
          registry-token: ${{ secrets.CARGO_TOKEN }}
          ignore-unpublished-changes: true
