name: Release Package
permissions:
  contents: read
  pages: write 
on:
  push:
    branches:
      - main
      - master
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: cargo publish
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }} --allow-dirty
